### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by hbellafkir** [timmh/MegaDetectorLite#1]
After installing all the requirements, the Onnx exporter gives a runtime error: 
`RuntimeError: yolort.runtime.y_onnxruntime._set_providers requires module: onnxruntime`

Do you have any idea what is causing this?

**Comment by timmh** [comment]
`onnxruntime` was missing from the requirements file, which is fixed by 888e090. It's only used for verifying whether the predictions of the exported model matches the predictions of the original model. Feel free to pull and try again, but your exported model should already work fine.
